name: docker

on:
  push:
    branches:
      - '[^/]+/[^/]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          maven_apk_version=(${branch_name//// })
          jdk_apk_package=$(basename $branch_name)
          echo "maven_apk_version=$maven_apk_version" >> $GITHUB_ENV
          echo "jdk_apk_package=$jdk_apk_package" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: intension/docker-dind-maven:${{ env.maven_apk_version }}-${{ env.jdk_apk_package }}
          build-args: |
            MAVEN_APK_VERSION=${{ env.maven_apk_version }}
            JDK_APK_PACKAGE=${{ env.jdk_apk_package }}
